#ifndef classType_h
#define classType_h


enum ClassType { IOBUFFER = 0, DELIMFIELDBUFFER, FIXEDFIELDBUFFER, LENGTHFIELDBUFFER,
    BUFFERFILE, RECORDFILE, STUDENT, COURSEREGISTRATION };


#endif /* classType_h */
