#ifndef classType_h
#define classType_h


enum ClassType { IOBUFFER = 0, DELIMFIELDBUFFER, FIXEDFIELDBUFFER,
    BUFFERFILE, RECORDFILE, STUDENT, TEXTINDEX, TEXTINDEXBUFFER, TEXTINDEXEDFILE };


#endif /* classType_h */
